# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos-6.6-x86_64"

  # 定义 master
  config.vm.define :hbmaster do |hbmaster_config|
    #hbmaster_config.vm.network :public_network, ip: "193.168.11.7"
    hbmaster_config.vm.network :private_network, ip: "172.16.1.7"
    hbmaster_config.vm.hostname = "data-1-1"
    hbmaster_config.vm.provision "shell", inline: <<-SHELL
      #sudo ip addr add 10.0.10.7/24 dev eth2
      ip ad |grep 'inet '
      
      # set ssh root login
      sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
      sudo /etc/init.d/sshd reload
      # set root password
      echo '123456' | sudo passwd --stdin root
    SHELL
    config.vm.provider :virtualbox do |vb|
      vb.name = "hbmaster"
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.cpus = 2
    end
  end

  # 定义 backup
  config.vm.define :hbbackup do |hbbackup_config|
    #hbbackup_config.vm.network :public_network, ip: "192.168.11.8"
    hbbackup_config.vm.network :private_network, ip: "172.16.1.8"
    hbbackup_config.vm.hostname = "data-1-2"
    hbbackup_config.vm.provision "shell", inline: <<-SHELL
      #sudo ip addr add 10.0.10.8/24 dev eth2
      ip ad |grep 'inet '
      
      # set ssh root login
      sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
      sudo /etc/init.d/sshd reload
      # set root password
      echo '123456' | sudo passwd --stdin root
    SHELL
    hbbackup_config.vm.provider "virtualbox" do |vb|
      vb.name = "hbbackup"
    end
  end
end